export const USER_REQUEST = 'STORY_REQUEST';
export const USER_SUCCESS = 'STORY_SUCCESS';
export const USER_FAILURE = 'STORY_FAILURE';
export const FOLLOWING_REQUEST = 'FOLLOWING_REQUEST';
export const FOLLOWING_SUCCESS = 'FOLLOWING_SUCCESS';
export const FOLLOWING_FAILURE = 'FOLLOWING_FAILURE';
